name: es-rl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pytorch
  - cpuonly
  - pyyaml
  - pip:
      - gymnasium==0.29.1
      - mujoco==3.1.1
      - gymnasium[mujoco]
